### PR TITLE
Update CODEOWNERS

### PR DESCRIPTION
**Pull request by urvika-v**
Adding urvika

#### What type of PR is this?

Add one of the following kinds:
* bug
* correction
* enhancement/feature
* cleanup
* documentation
* subproject management
* tests

#### Which issue(s) this PR fixes:

Fixes #

#### Changelog input

```
 release-note

```

#### Additional documentation 

This section can be blank.

```
docs

```

### CODE REVIEW

**Comment by hdamker** [comment]
@camaraproject/connectivity-insights_maintainers, it is the responsibility of the Maintainers to define the codeowners for the repository, please indicate your support with your approval. Thanks.

**Comment by hdamker** [comment]
@urvika-v please subscribe in the meantime already to https://lists.camaraproject.org/g/sp-coi

**Comment by Kevsy** [comment]
Hi @hdamker , happy to approve but I see this error in the commit:

 "⚠️   This CODEOWNERS file contains errors
 Unknown owner on line 8: make sure @urvika-v exists and has write access to the repository"
 
 Please can you take a look?

**Comment by hdamker** [comment]
> Hi @hdamker , happy to approve but I see this error in the commit:
> 
> "⚠️ This CODEOWNERS file contains errors Unknown owner on line 8: make sure @urvika-v exists and has write access to the repository"
> 
> Please can you take a look?

@Kevsy the reason is that @urvika-v hasn't yet write access to the repository. But that I can grant only after I now that this PR has the support of the Maintainers. Thanks for your confirmation.

**Review by maheshc01 — APPROVED** [review]

**Comment by maheshc01** [comment]
> > Hi @hdamker , happy to approve but I see this error in the commit:
> > "⚠️ This CODEOWNERS file contains errors Unknown owner on line 8: make sure @urvika-v exists and has write access to the repository"
> > Please can you take a look?
> 
> @Kevsy the reason is that @urvika-v hasn't yet write access to the repository. But that I can grant only after I now that this PR has the support of the Maintainers. Thanks for your confirmation.

This PR has my support @hdamker . have approved it.

**Review by hdamker — APPROVED** [review]

**Comment by hdamker** [comment]
@urvika-v the updated Codeowner file will get valid as soon as you have accepted the invitation to get a member of the CAMARA Organization (and the @camaraproject/connectivity-insights_codeowners team). 
cc: @Kevsy @maheshc01

**Pull request merged**
