### PR TITLE
Update MAINTAINERS.MD

### PR DESCRIPTION
**Pull request by maheshc01**
adding Kevin Smith as new maintainer

#### What type of PR is this?

Add one of the following kinds:
* bug
* correction
* enhancement/feature
* cleanup
* documentation
* subproject management
* tests

#### Which issue(s) this PR fixes:

Fixes #

#### Changelog input

```
 release-note

```

#### Additional documentation 

This section can be blank.

```
docs

```

### CODE REVIEW

**Comment by MarkusKuemmerle** [comment]
@maheshc01 @hdamker : Kevin is not part of the Sub Project (not at the mailing list), that should be a prerequisite to become maintainer or code owner. I'll in invite him...

**Comment by maheshc01** [comment]
Can you please point me to the documentation where this process is
explained?
Also in general git mgmt CAMARA guidelines document is available.

<http://www.verizon.com>

Mahesh Chapalamadugu

Principal Member Technical Staff

MEC Planning and Architecture

**Comment by MarkusKuemmerle** [comment]
@maheshc01 : You can look into the Project Charter. To become a maintainer an individual shall show active contribution to a Sub Project at least of 3 months. For a new Sub Project that's not possible, but it means at least to be part of the Sub Project :-)

**Comment by hdamker** [comment]
@maheshc01 Beside the Project Charter please have a look into https://github.com/camaraproject/Governance/blob/main/ProjectStructureAndRoles.md and into https://github.com/camaraproject/Governance/blob/main/CONTRIBUTING.md.

Later relevant is also https://github.com/camaraproject/Commonalities/blob/main/documentation/Camara_Versioning_Guidelines.md

**Comment by maheshc01** [comment]
Thank you @hdamker

**Pull request merged**
